apiVersion: v1
kind: ConfigMap
metadata:
  name: massload-config
  namespace: massload
  labels:
    app.kubernetes.io/name: massload
data:
  # Backend config
  RUST_LOG: "info"
  # Frontend runtime config
  BACKEND_URL: "http://massload-backend:3000"
  BLOCKCHAIN_RPC: "wss://node-dev.allfeat.io"

