apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: massload

resources:
  - ../../

configMapGenerator:
  - name: massload-config
    behavior: merge
    literals:
      - BACKEND_URL=https://api.massload-dev.allfeat.org
      - BLOCKCHAIN_RPC=wss://node-dev.allfeat.io

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: massload-dev.allfeat.org
      - op: replace
        path: /spec/rules/1/host
        value: api.massload-dev.allfeat.org
    target:
      kind: Ingress
      name: massload-ingress

